### FIND ALL
GET http://localhost:3000/api/cuotasMensuales

### CREATE Cuota Mensual
# @name CreateCuotaMensual
POST http://localhost:3000/api/cuotasMensuales
Content-Type: application/json

{
  "socio": 1,
  "mes": 9,
  "anio": 2025,
  "monto": 25000,
  "pagada": null,
  "fechaPago": null
}

### ID
@id = {{CreateCuotaMensual.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/cuotasMensuales/{{id}}

### UPDATE Cuota mensual (El socio paga su cuota)
PUT http://localhost:3000/api/cuotasMensuales/{{id}}
Content-Type: application/json

{
  "pagada": true,
  "fechaPago": "2025-09-04"
}


### CREATE Cuota mensual to delete
# @name createCuotaMensualToDelete
POST http://localhost:3000/api/cuotasMensuales
Content-Type: application/json

{
  "socio": 2,
  "mes": 8,
  "anio": 2025,
  "monto": 25000,
  "pagada": null,
  "fechaPago": null
}

### DELETE
@idToDelete = {{createCuotaMensualToDelete.response.body.data.id}}

DELETE http://localhost:3000/api/cuotasMensuales/{{idToDelete}}