### obtener todos los tiposEmbarcacion
GET http://localhost:3000/api/tiposEmbarcacion


### ID
@id = {{createTipoEmbarcacion.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/tiposEmbarcacion/{{id}}



###POST TIPOEMBARCACION TO DELETE
# @name createTipoEmbarcacionToDelete
POST http://localhost:3000/api/tiposEmbarcacion
Content-Type: application/json

{
  "nombre": "Lancha",
  "esloraMaxima": 10
}


### POST
# @name createTipoEmbarcacion
POST http://localhost:3000/api/tiposEmbarcacion
Content-Type: application/json

{
  "nombre": "Catamaran",
  "esloraMaxima": 10
}

### POST
# @name createTipoEmbarcacion
POST http://localhost:3000/api/tiposEmbarcacion
Content-Type: application/json

{
  "nombre": "Barco pirata",
  "esloraMaxima": 15
}


### PUT
PUT http://localhost:3000/api/tiposEmbarcacion/{{id}}
Content-Type: application/json

{
  "nombre": "Velero",
  "esloraMaxima": 30
}



### DELETE
@idToDelete = {{createTipoEmbarcacionToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/tiposEmbarcacion/{{idToDelete}}
