### obtener todos los tiposEmbarcacion
GET http://localhost:3000/api/tiposEmbarcacion



### obtener velero
GET http://localhost:3000/api/tiposEmbarcacion/1



### Crear catamaran
POST http://localhost:3000/api/tiposEmbarcacion
Content-Type: application/json

{
  "nombre": "Catamaran",
  "esloraMaxima": 10
}



### modificar a velero
PUT http://localhost:3000/api/tiposEmbarcacion/1
Content-Type: application/json

{
  "nombre": "Velero",
  "esloraMaxima": 30
}

### modificar por patch
PATCH http://localhost:3000/api/tiposEmbarcacion/1
Content-Type: application/json

{
  "esloraMaxima": 25
}



### borrar a velero
DELETE http://localhost:3000/api/tiposEmbarcacion/1
