### obtener todos los socios
GET http://localhost:3000/api/socios


### ID
@id = {{createSocio.response.body.data.id}}

###GET ONE
GET http://localhost:3000/api/socios/{{id}}

### POST SOCIO TO DELETE
# @name createSocioToDelete
POST http://localhost:3000/api/socios
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "dni": "20.123.456",
  "email":"juan.perez@gmail.com",
  "telefono": "3412837598"
}


### POST
# @name createSocio
POST http://localhost:3000/api/socios
Content-Type: application/json

{
  "nombre": "Lionel Messi",
  "dni": "33.016.244",
  "email":"lio.messi@gmail.com",
  "telefono": "3412837598"
}




### PUT
PUT http://localhost:3000/api/socios/{{id}}
Content-Type: application/json

{
  "nombre": "Lionel Andres Messi Cuccittini",
  "email":"lionel.messi@gmail.com"
}



### DELETE
@idToDelete = {{createSocioToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/socios/{{idToDelete}}

