### obtener todos los admin
GET http://localhost:3000/api/administradores

### crear otro admin
# @name createAdministrador
POST http://localhost:3000/api/administradores
Content-Type: application/json

{
  "nombre": "Alexis",
  "apellido": "Galasco",
  "dni": "43842560",
  "email":"alexis.galasco0@gmail.com",
  "password":"123456789"
}

### ID
@administradorId = {{createAdministrador.response.body.data.id}}

###GET ONE
GET http://localhost:3000/api/administradores/{{administradorId}}

### modificar a administrador
PUT http://localhost:3000/api/administradores/{{administradorId}}
Content-Type: application/json

{
  "password": "123456"
}

### borrar a administrador
DELETE http://localhost:3000/api/administradores/{{administradorId}}