### obtener todos los admin
GET http://localhost:3000/api/administradores

### crear otro admin
# @name createAdministrador
POST http://localhost:3000/api/administradores
Content-Type: application/json

{
  "nombre": "Teo",
  "apellido": "De Elia",
  "email":"teo12@gmail.com",
  "password":"@Mess1"
}

### ID
@id = {{createAdministrador.response.body.data.id}}

###GET ONE
GET http://localhost:3000/api/administradores/{{id}}

### modificar a administrador
PUT http://localhost:3000/api/administradores/{{id}}
Content-Type: application/json

{
  "nombre": "Teofilo",
  "password":"edlp412" 
}


### borrar a administrador 1
DELETE http://localhost:3000/api/administradores/{{id}}